 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA', '.' ]
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - '-c'
   - 'export DATABASE_URL=$$DATABASE_URL && export ROCKET_DATABASES=$$ROCKET_DATABASES'
   - 'run'
   - 'deploy'
   - 'website'
   - '--image'
   - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
   secretEnv: ['DATABASE_URL', 'ROCKET_DATABASES']
 images:
 - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
 timeout: 1200s
 availableSecrets:
  secretManager:
  - versionName: projects/904165140417/secrets/newsroomDBUrl/versions/4
    env: 'DATABASE_URL'
  - versionName: projects/904165140417/secrets/ROCKET_DATABASES/versions/1
    env: 'ROCKET_DATABASES'