 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA', '.' ]
   secretEnv: ['ADMINS']
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'beta'
   - 'run'
   - 'deploy'
   - 'website'
   - '--image'
   - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
   - '--set-secrets'
   - 'DATABASE_URL=newsroomDBUrl:latest,ROCKET_DATABASES=ROCKET_DATABASES:latest'
 images:
 - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
 timeout: 1200s
 availableSecrets:
  secretManager:
  - versionName: projects/904165140417/secrets/ADMINS/versions/1
    env: 'ADMINS'