 steps:
 # Build the container image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA', '.' ]
 # Push the container image to Container Registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA']
 # Deploy container image to Cloud Run
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   entrypoint: gcloud
   args:
   - 'run'
   - 'deploy'
   - 'website'
   - '--image'
   - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
   - '--region'
   - 'us-central1'
   - '--platform'
   - 'managed'
   options:
      env:
        - name: 'DATABASE_URL'
          valueFrom:
            secretKeyRef:
              key: '4'
              name: 'newsroomDBUrl'
        - name: 'ROCKET_DATABASES'
          valueFrom:
            secretKeyRef:
              key: '1'
              name: 'ROCKET_DATABASES'
 images:
 - 'gcr.io/$PROJECT_ID/website:$COMMIT_SHA'
 timeout: 1200s